#lang racket
(require 2htdp/image)
(require lang/posn)

(provide (all-defined-out))
;=====================================================
;; definations
;=====================================================
(struct interface (image bindings))
(struct Paddle(x y H W vx) #:mutable)
(struct Ball(x y vx vy r) #:mutable)
(struct powerup (name vel-y x y) #:mutable)
(struct 2d(up down) #:mutable)
(struct vec(x y) #:mutable)
(struct WS(pdl1 pdl2 ball bricks powers chance score pause lives level mode) #:mutable)
;========================================================
;========================================================

(define-values (width height BW BH bw bh)
  (values 700 500 386 386 15 6))

(define brick1 (bitmap "images/green-brick.png"))
(define brick2 (bitmap "images/yellow-brick.png"))
(define brick3 (bitmap "images/red-brick.png"))

(define enlarge (text "<-->" 18 'green))
(define compress (text ">-<" 18 'red))
(define livei (text "+1" 18 'green))
(define lived (text "-1" 15 'red))

(define side-panel1 (place-images (list (text "Score" 18 'blue)
                                       (rectangle 90 30 'outline 'red)
                                       (text "Lives" 18 'blue)
                                       (rectangle 90 30 'outline 'red)
                                       (text "Level" 18 'blue)
                                       (rectangle 90 30 'outline 'red)
                                       (text "Back" 18 'red)
                                       (rectangle 90 30 'solid 'green))
                                 (list (make-posn 50 20)
                                       (make-posn 50 45)
                                       (make-posn 50 80)
                                       (make-posn 50 105)
                                       (make-posn 50 230)
                                       (make-posn 50 255)
                                       (make-posn 50 300)
                                       (make-posn 50 300))
                                 (place-image (rectangle 100 500 'outline 'black) 50 250
                                              (rectangle 101 501 'solid 'yellow))))
(define side-panel2 (place-images (list (text "Score" 18 'blue)
                                       (rectangle 90 30 'outline 'red)
                                       (text "Lives" 18 'blue)
                                       (rectangle 90 30 'outline 'red))
                                 (list (make-posn 50 450)
                                       (make-posn 50 475)
                                       (make-posn 50 390)
                                       (make-posn 50 415))
                                 side-panel1))

(define background1 (beside (empty-scene width height 'yellow) side-panel1))
(define background2 (beside (empty-scene width height 'yellow) side-panel2))

(define start-image (place-images (list (rectangle 150 30 'outline 'red)
                                        (text "PLAY" 20 'brown)
                                        (rectangle 150 30 'outline 'red)
                                        (text "EXIT" 20 'brown))
                                  (list (make-posn 400 220)
                                        (make-posn 400 220)
                                        (make-posn 400 270)
                                        (make-posn 400 270))
                                  (empty-scene 800 500)))

(define on-play-image (place-images (list (rectangle 150 30 'outline 'red)
                                          (text "Single Player" 20 'brown)
                                          (rectangle 150 30 'outline 'red)
                                          (text "Double PLayer" 20 'brown)
                                          (rectangle 75 25 'outline 'red)
                                          (text "Back" 18 'brown))
                                    (list (make-posn 400 220)
                                          (make-posn 400 220)
                                          (make-posn 400 270)
                                          (make-posn 400 270)
                                          (make-posn 600 450)
                                          (make-posn 600 450))
                                    (empty-scene 800 500)))

(define on-single-image (place-images (list (rectangle 150 30 'outline 'red)
                                            (text "level 1" 20 'brown)
                                            (rectangle 150 30 'outline 'red)
                                            (text "level 2" 20 'brown)
                                            (rectangle 150 30 'outline 'red)
                                            (text "level 3" 20 'brown)
                                            (rectangle 150 30 'outline 'red)
                                            (text "level 4" 20 'brown)
                                            (rectangle 150 30 'outline 'red)
                                            (text "level 5" 20 'brown)
                                            (rectangle 75 25 'outline 'red)
                                            (text "Back" 18 'brown))
                                      (list (make-posn 400 120)
                                            (make-posn 400 120);
                                            (make-posn 400 170)
                                            (make-posn 400 170);
                                            (make-posn 400 220)
                                            (make-posn 400 220);
                                            (make-posn 400 270)
                                            (make-posn 400 270);
                                            (make-posn 400 320)
                                            (make-posn 400 320);
                                            (make-posn 600 450)
                                            (make-posn 600 450))
                                      (empty-scene 800 500)))

(define on-double-image (place-images (list (rectangle 150 30 'outline 'red)
                                            (text "With Computer" 20 'brown)
                                            (rectangle 150 30 'outline 'red)
                                            (text "Offline" 20 'brown)
                                            (rectangle 75 25 'outline 'red)
                                            (text "Back" 18 'brown))
                                      (list (make-posn 400 220)
                                            (make-posn 400 220)
                                            (make-posn 400 270)
                                            (make-posn 400 270)
                                            (make-posn 600 450)
                                            (make-posn 600 450))
                                      (empty-scene 800 500)))
(define developing (place-image (text "Under Developement" 30 'brown)
                                400 250
                                (empty-scene 800 500 'yellow)))